<?
//include_once('groupings/bootstrap.php');
Assets::import('bootstrap');
Assets::add("jquery.min.js","http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/");
Assets::add("jquery-ui.js","http://jquery-ui.googlecode.com/svn/tags/1.8.19/ui/");
Assets::add("json2.js","http://content.sandbox.steepleconnect.net/js/");
Assets::add("jquery.url.js","http://content.sandbox.steepleconnect.net/js/");
Assets::add("jquery.placeholder.min.js","http://content.sandbox.steepleconnect.net/js/");
Assets::add("router.js");
Assets::add("cookie_jar.js");
Assets::add("football.js");
Assets::add_style("pickem.php");
?>
